### ISSUE TITLE
Fetching list of secret directories failed: {"errors":[]}

### ISSUE THREAD

**Issue by Razva** [mulbc/vaultPass#13]
Per the documentation I've created a `vaultpass` directory, a `org` directory and added a secret in `sitename.com`

The full path would be `/vaultpass/org/sitename.com`. I've also created `/secret/vaultpass/org/sitename.com` (because the documentation specifies `/secret` as well).

In order to test this, I've allowed full rw rights to the test user and logged in via UI and CLI; the user has proper access.

Still, after logging into Vault via your Plugin, I'm getting this:

`Fetching list of secret directories failed: {"errors":[]}`

Any hints?

**Comment by mulbc** [comment]
@Razva please try to call the top level folder `vaultPass` (case sensitive)

**Comment by mulbc** [comment]
Hey @Razva - just checking in... has your issue been resolved? I'll close this issue due to inactivity if you don't respond till Monday

**Comment by Razva** [comment]
I'll give it a shot tomorrow and get back to you. Thank you!

**Comment by mulbc** [comment]
Closed due to inactivity

**Comment by afteroot** [comment]
problem still exist
