### ISSUE TITLE
paths have changed

### ISSUE THREAD

**Issue by Ogy** [mulbc/vaultPass#14]
Hello, i think paths have changed
even when i apply admin policy im getting 

Fetching list of secret directories failed: {"errors":["no handler for route 'secret/metadata/vaultPass/'"]}

UI works as expected with userpass user with admin policy

Vault v1.1.1
Consul v1.5.2

Thanks for your time in advance

**Comment by mulbc** [comment]
Do you have the KV mounted at /secret? Are you using the v1 or v2 access_policy?

**Comment by Ogy** [comment]
Hello,
must be KV version 2 
and path must be 

secret/vaultPass

it works then
Many thanks
