### ISSUE TITLE
Make the lookup path configurable

### ISSUE THREAD

**Issue by mvdkleijn** [mulbc/vaultPass#16]
**Is your feature request related to a problem? Please describe.**
We have a large set of secrets already in vault. These are not on the standard vaultPass location.

**Describe the solution you'd like**
Let me configure the path in Vault where vaultPass should be looking.

**Describe alternatives you've considered**
Looking for another plugin....

**Comment by mulbc** [comment]
Thanks for the issue - I am aware that this might be an issue for people who already have kv information in their Vault... On the other hand, the plugin was intentionally kept simple.

If this is important to you, please send in a PR for this, I'll be happy to review and merge.
