### ISSUE TITLE
Fetching list of secret directories failed

### ISSUE THREAD

**Issue by 80kk** [mulbc/vaultPass#17]
Getting 
`Fetching list of secret directories failed: {"errors":["no handler for route 'secret/metadata/vaultPass/'"]}`
error.

No matter if I enable kv secret engine with path `secret` or `secret/VaultPass` I am getting either the error above or just: `Fetching list of secret directories failed: {"errors":[""]}`

Both Firefox and Chrome. Vault 1.2.3 with DynamoDB backend.

**Comment by mulbc** [comment]
The secret engine is supposed to run on the `secret` path, with a folder inside called `VaultPass` inside of that folder, you would create subfolders for the access groups that share these secrets

Does that help?

**Comment by kecskemethy** [comment]
or you might need to enable this secret path first e.g.
`vault secrets enable -path=secret/ kv-v2`

**Comment by mulbc** [comment]
closing this old issue ;)

**Comment by exesse** [comment]
Will post this for history reasons. If you created an *org1* user and policies via the UI, there will be an additional step to associate the policies with the user:

> vault write auth/userpass/users/org1/policies policies="default,org1"
