### ISSUE TITLE
Make the Path configureable

### ISSUE THREAD

**Issue by nicolasberens** [mulbc/vaultPass#20]
Since we have a slightly different vauult structure, it might be great if you could make the path variable, instead of `secret/vaultPass`

**Comment by anxstj** [comment]
A configurable path would be a great enhancement. +1

**Comment by afteroot** [comment]
@rtznprmpftl  as i think you need to change only `vaultPass` instead of `secret/vaultPass` ? or you need to get all kv ?
ex:
```
vault secrets list
Path          Type         Accessor              Description
----          ----         --------              -----------
cubbyhole/    cubbyhole    cubbyhole_0fdf90cc    per-token private secret storage
git_gogs/     kv           kv_8bd7cd80           n/a
secret/       kv           kv_0a2ed64b           n/a
```
```
vault kv list secret/vaultPass
Keys
----
main/
```

**Comment by seyfbarhoumi** [comment]
I agree, that would be a great feature !

**Comment by SamuZad** [comment]
It would also be neat if the plugin could read out of the cubbyhole.. So that personal secrets that no-one else has access to could also be used.

**Comment by mulbc** [comment]
Hi all, the path is now configurable:
https://github.com/mulbc/vaultPass/releases/tag/v2.3.3

Release is in review and will be published very soon
