### ISSUE TITLE
Allow OIDC Logins

### ISSUE THREAD

**Issue by gabecazares-cc** [mulbc/vaultPass#21]
**Is your feature request related to a problem? Please describe.**
I can't use this plugin due to not allowing for alternative logs besides user/pass; such as OIDC login

**Describe the solution you'd like**
I'd like the option to log in with an OIDC provider in the plugin configuration. My vault is only accessible via an OIDC provider so I can't use this plugin.

**Describe alternatives you've considered**
There are none, unfortunately. Maybe someday, I'll learn the languages used in this project so I can assist =)

**Additional context**
![image](https://user-images.githubusercontent.com/74260849/108259066-f4347180-711d-11eb-8736-2832044ea85a.png)

**Comment by Yayg** [comment]
:+1: this would be a must! I hope this will arrive soon! :D

**Comment by Bredec** [comment]
@mulbc   any plans to support this ?

**Comment by mulbc** [comment]
Sorry for the late reply - There've been a couple of OIDC / Single-Sign-On requests. Unfortunately I don't know how I could support it with an Extension (I'm not actually a front-end developer ;) )
If I'd give you the option to login with a token, would that help? You can use the Vault Web UI or Vault CLI to generate User Tokens

**Comment by Bredec** [comment]
@mulbc absolutely. Go ahead!

**Comment by mulbc** [comment]
The new version I just released and submitted to the Chrome & Firefox stores should solve your issue - please reopen this issue if it does not
