### ISSUE TITLE
Count of secrets 

### ISSUE THREAD

**Issue by afteroot** [mulbc/vaultPass#23]
Could you please add count of secrets via setBadgeText

So if in Vault any of secrets exists so we can disaply it on icon with setBadgeText ex:
```
chrome.tabs.onActivated.addListener(function() {
  chrome.storage.sync.set({number: 1}, function() {
    chrome.browserAction.setBadgeText({text: "3"+Math.random()});
  });
});
```

**Comment by mulbc** [comment]
That's a good idea! Let me see if I can add that soon

**Comment by afteroot** [comment]
Sound's good) waiting )

**Comment by afteroot** [comment]
and also please make check of this `https://github.com/sa2rn/vaultPass` made some modify

**Comment by mulbc** [comment]
I've created https://github.com/mulbc/vaultPass/pull/24 to get those changes downstream, thanks for letting me know

**Comment by afteroot** [comment]
Yep, sure .. wait a while .. im on vacation )

**Comment by mulbc** [comment]
c4fea64 implements the badgeText now and I also merged the PR

Will (try to) get this new version into the Google and Firefox store soon

**Comment by afteroot** [comment]
Looks good!
