### ISSUE TITLE
Question - Does the plugin on chrome store work out of the box

### ISSUE THREAD

**Issue by moedawood** [mulbc/vaultPass#27]
Hi 

Just a question , does the plugin on the chrome store work out of the box , I seem to be getting an error 

- Cannot read body stream

Am I missing something ?

**Comment by mulbc** [comment]
It should work out of the box and show you a window like this when you click the VaultPass icon:
![image](https://user-images.githubusercontent.com/131446/150319688-6586cebf-0c5f-4458-9230-de2e4a497d80.png)
After seeing this, you should head over to the options page to log into your Vault instance

**Comment by moedawood** [comment]
> It should work out of the box and show you a window like this when you click the VaultPass icon: ![image](https://user-images.githubusercontent.com/131446/150319688-6586cebf-0c5f-4458-9230-de2e4a497d80.png) After seeing this, you should head over to the options page to log into your Vault instance

Hi 

The current version on chrome gives me the following error 

When I hit login

"Failed to execute 'text' on 'Response': body stream already read"

**Comment by mulbc** [comment]
Would you be able to show me a screenshot or video of your issue? I currently can't reproduce it. 

If you want to test it with a test Vault instance you'll find the `start_dev_environment.sh` script in this repo. You can login to that Vault at URL `http://localhost:8200` with the user `mitchellh`, password `foo` and Auth Mountpoint `userpass`

**Comment by moedawood** [comment]
> Would you be able to show me a screenshot or video of your issue? I currently can't reproduce it.
> 
> If you want to test it with a test Vault instance you'll find the `start_dev_environment.sh` script in this repo. You can login to that Vault at URL `http://localhost:8200` with the user `mitchellh`, password `foo` and Auth Mountpoint `userpass`

Hi 

please see attached

https://user-images.githubusercontent.com/62351382/150477456-e544fdeb-d145-4bd1-996d-8f1a171ab733.mp4

**Comment by mulbc** [comment]
Does the same happen with the `mitchellh` test user? Else, could you share how you created the browser test user?

**Comment by moedawood** [comment]
> Does the same happen with the `mitchellh` test user? Else, could you share how you created the browser test user?

Hi 

So I have setup again and seem to be getting the same error

First i create a secret as root user via token login 

Next I create a policy with read and list capabailities

**Comment by mulbc** [comment]
Thanks for pointing me to the Vault Tutorial - I was not aware that Hashicorp uses part of my code for their tutorials

I still think that your problem is due to a Policy issue... You never responded if the mitchellh test user works for you. When you use the 'start_dev_environment.sh' script to start a local Vault instance, the mitchellh user comes with a test secret for the URL google.com. Maybe you want to try that out again?

If everything fails, would you be open for a screen-sharing session next week so I can debug this on your end?

**Comment by moedawood** [comment]
> Thanks for pointing me to the Vault Tutorial - I was not aware that Hashicorp uses part of my code for their tutorials
> 
> I still think that your problem is due to a Policy issue... You never responded if the mitchellh test user works for you. When you use the 'start_dev_environment.sh' script to start a local Vault instance, the mitchellh user comes with a test secret for the URL google.com. Maybe you want to try that out again?
> 
> If everything fails, would you be open for a screen-sharing session next week so I can debug this on your end?

Hi 
Yes sure 

Let me give it a go and see what happens

**Comment by ahernandez411** [comment]
I am also seeing this behavior. I'm attempting to use LDAP to login

**Comment by moedawood** [comment]
Good day,

Thank-you for your email, in order to streamline support requests and serve you better, we utilise a support ticket system, a ticket has been created for you and a member of our support team will be assigned to your request and will follow-up with you as soon as possible.

Please note that our business hours are:
Mon - Fri : 08:00 - 16:00
Sat + Sun : Closed
Public Holidays: Closed

Kind Regards
Your Friendly PiShop Team

[https://ci3.googleusercontent.com/proxy/_qrIf5zI7cjL1Cbvd8hYhGwdGiz4CZNzBJLUZQyS8Uyp3V03mUhILWJKOCQzh8U7xFCmNwgnmo2DXGfVhYkYexRs=s0-d-e1-ft#https://www.pishop.co.za/email-sig-logo-300.jpg]



REF: eeff2e1976a71ad01066a13e1bbb17d9:3745
