### ISSUE TITLE
 The message port closed before a response was received.

### ISSUE THREAD

**Issue by srinidhikrs** [mulbc/vaultPass#29]
**Describe the bug**
The following error occurs in background.js:
 The message port closed before a response was received.
**To Reproduce**
On Opening the portal for which username and password is stored in vault.

**Expected behavior**
Autofill to happen in username and password

**Browser (please complete the following information):**
 - OS: Ubuntu 21
 - Type : Chrome
 - Version Version 99.0.4844.51 (Official Build) (64-bit)

**Additional context**
Auto filling is not happening

**Comment by mulbc** [comment]
I'm closing this, since this is fairly old by now and we've improved the credentials filling now
