### ISSUE TITLE
Add support for Azure AD

### ISSUE THREAD

**Issue by GolanTrevize10** [mulbc/vaultPass#30]
**Is your feature request related to a problem? Please describe.**
The only authentication method to vault is via username and password. If I want to share passwords within a team, this is not very convenient.

**Describe the solution you'd like**
Integration with Azure AD. I can grant permissions on secrets to my team members and they can grab secrets seamlessly using SSO AAD authentication

**Describe alternatives you've considered**

**Additional context**

**Comment by mulbc** [comment]
The new version I just released and submitted to the Chrome & Firefox stores should solve your issue - please reopen this issue if it does not
