### ISSUE TITLE
Readme update for: token grabber usage 

### ISSUE THREAD

**Issue by SamuZad** [mulbc/vaultPass#37]
~~Are there any plans to make the plugin OIDC login compatible?~~

~~The current functionality is already super useful, but an having OIDC login support would be incredible. Especially since other than LDAP, this is probably the most organization-oriented login method.~~

EDIT: I see that something similar exists in the closed issues, but I am unsure of how I'd be able to get it to work.

EDIT2: I see! I had to be on the Vault window 😅 @mulbc would you mind if I updated the main page readme to make this clear?

**Comment by mulbc** [comment]
Glad you were able to help yourself ;) I'll close this issue, but PRs for the Readme are always very welcome!
