### ISSUE TITLE
Periodically renew vault auth token

### ISSUE THREAD

**Issue by eric-eisenhart** [mulbc/vaultPass#53]
**Is your feature request related to a problem? Please describe.**
Kind of a 2-parter to get to the problem I encounter:
1. I use the "Get token from Vault" option of vaultPass, because all of our auth methods for users have MFA on them.
2. If I don't regularly interact with the Vault web UI during the day, the token that vaultPass is using expires.

The result is that if I'm not having to use Vault and/or vaultPass regularly, I have to logout and back into vaultPass every time I need to use vaultPass.

**Describe the solution you'd like**
I believe if vaultPass periodically renewed the token it's using, it would significantly extend the time between required re-authentication.

I believe this can be done with a POST to /auth/token/renew-self with a payload like
```json
{
  "increment": "7d"
}
```

The JSON payload that it returns includes the lease duration `"lease_duration": 3600`

Would, of course, require that something run on a timer to periodically call that. Could either do it as some fraction of the lease_duration returned or could be an additional config item.

Docs: https://developer.hashicorp.com/vault/api-docs/auth/token#renew-a-token

**Describe alternatives you've considered**
- Setting up Vault Agent to use its token renewal functionality, and using same auth token in vaultPass.
- Setting up Vault Proxy and configuring vaultPass to access Vault via that proxy.

**Additional context**
Seems to correlate to the vault web UI showing a message like:
> We've stopped auto-renewing your token due to inactivity. It will expire on [date time].

**Comment by mulbc** [comment]
We actually have a function (thanks to the community) that tried to refresh the token in the background already.
You can see the code here:
https://github.com/mulbc/vaultPass/blob/8f78395e41b51dd208c6f48d4d0846d9d521c763/background.js#L149

You could check out the console output of the Extension to see if that actually happens in your case.

One possibility is that your Vault administrator has prohibited or limited the token renewal and we can't do the renewal due to that. Any chance this is happening for you?

**Comment by eric-eisenhart** [comment]
> You could check out the console output of the Extension to see if that actually happens in your case.

Ok, thanks, I'll take a look at that. It's entirely possible I'm running into something else. I'll open a new issue if I find anything that looks like it could be fixed with changes to vaultPass.

> One possibility is that your Vault administrator has prohibited or limited the token renewal and we can't do the renewal due to that. Any chance this is happening for you?

I'm actually the main Vault admininistrator. The token renewal limit is 30 days, so probably not that.
